# Generated by Django 5.1.3 on 2024-12-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_csvdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csvdata',
            old_name='column3',
            new_name='ch_id',
        ),
        migrations.RenameField(
            model_name='csvdata',
            old_name='column4',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='column1',
        ),
        migrations.RemoveField(
            model_name='csvdata',
            name='column2',
        ),
        migrations.AddField(
            model_name='csvdata',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
