# Generated by Django 5.1.3 on 2024-12-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_column3_csvdata_ch_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='name_link_chan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_id', models.IntegerField()),
                ('ch_name', models.CharField(max_length=255)),
                ('ch_link', models.CharField(max_length=255)),
                ('reated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
