# Generated by Django 5.1.3 on 2024-12-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_name_link_chan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255)),
                ('channel_url', models.URLField()),
            ],
        ),
    ]
